// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SponsorshipApproval.Infrastructure.Persistence;

#nullable disable

namespace SponsorshipApproval.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521192307_InitialDomainSchema")]
    partial class InitialDomainSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SponsorshipApproval.Domain.Requests.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("SponsorshipRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("sponsorship_request_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_object_key");

                    b.HasIndex("SponsorshipRequestId")
                        .HasDatabaseName("ix_attachments_sponsorship_request_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("SponsorshipApproval.Domain.Requests.SponsorshipRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("department");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<string>("ExpectedBenefit")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("expected_benefit");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("purpose");

                    b.Property<string>("Remarks")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remarks");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("requested_amount");

                    b.Property<string>("RequestorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("requestor_id");

                    b.Property<string>("RequestorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requestor_name");

                    b.Property<Guid>("SponsorshipTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sponsorship_type_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("updated_by");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_sponsorship_requests");

                    b.HasIndex("RequestorId")
                        .HasDatabaseName("ix_sponsorship_requests_requestor_id");

                    b.HasIndex("SponsorshipTypeId")
                        .HasDatabaseName("ix_sponsorship_requests_sponsorship_type_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sponsorship_requests_status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_sponsorship_requests_status_created_at");

                    b.ToTable("sponsorship_requests", (string)null);
                });

            modelBuilder.Entity("SponsorshipApproval.Domain.Requests.SponsorshipType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_sponsorship_types");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_sponsorship_types_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sponsorship_types_name");

                    b.ToTable("sponsorship_types", (string)null);
                });

            modelBuilder.Entity("SponsorshipApproval.Domain.Requests.WorkflowHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("actor_id");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Remarks")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remarks");

                    b.Property<Guid>("SponsorshipRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("sponsorship_request_id");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_workflow_history");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_workflow_history_actor_id");

                    b.HasIndex("SponsorshipRequestId")
                        .HasDatabaseName("ix_workflow_history_sponsorship_request_id");

                    b.HasIndex("SponsorshipRequestId", "OccurredAt")
                        .HasDatabaseName("ix_workflow_history_sponsorship_request_id_occurred_at");

                    b.ToTable("workflow_history", (string)null);
                });

            modelBuilder.Entity("SponsorshipApproval.Domain.Requests.Attachment", b =>
                {
                    b.HasOne("SponsorshipApproval.Domain.Requests.SponsorshipRequest", "SponsorshipRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("SponsorshipRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_sponsorship_requests_sponsorship_request_id");

                    b.Navigation("SponsorshipRequest");
                });

            modelBuilder.Entity("SponsorshipApproval.Domain.Requests.SponsorshipRequest", b =>
                {
                    b.HasOne("SponsorshipApproval.Domain.Requests.SponsorshipType", "SponsorshipType")
                        .WithMany("SponsorshipRequests")
                        .HasForeignKey("SponsorshipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sponsorship_requests_sponsorship_types_sponsorship_type_id");

                    b.Navigation("SponsorshipType");
                });

            modelBuilder.Entity("SponsorshipApproval.Domain.Requests.WorkflowHistory", b =>
                {
                    b.HasOne("SponsorshipApproval.Domain.Requests.SponsorshipRequest", "SponsorshipRequest")
                        .WithMany("WorkflowHistoryEntries")
                        .HasForeignKey("SponsorshipRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_history_sponsorship_requests_sponsorship_request_id");

                    b.Navigation("SponsorshipRequest");
                });

            modelBuilder.Entity("SponsorshipApproval.Domain.Requests.SponsorshipRequest", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("WorkflowHistoryEntries");
                });

            modelBuilder.Entity("SponsorshipApproval.Domain.Requests.SponsorshipType", b =>
                {
                    b.Navigation("SponsorshipRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
